### PR TITLE
Moved flex utility classes (to be used in wider context)

### PR DESCRIPTION
**Pull request by Paulus90**
Moved flexbox utility classes from grid partial to utility partial and removed the grid dependency, so these classes can be used in a wider context.

### CODE REVIEW

**Comment by Paulus90** [comment]
@dariusrosendahl wil jij deze reviewen?

**Comment by pascalalferink** [comment]
It agree it is a valid improvement.
I have one concern: most of the css-classes that are moved have an abbreviation before the hyphen, that correlates to the property that is styled. For instance all the classes starting with "jc-" are about the property justify-content.  

The classes .wrap and .nowrap don't have these abbreviations with hyphen. This makes the classname somewhat ambiguous, because it can also be interpreted as a css-classes that modifies the property white-space or word-break.

It think it would be an additional improvement to prefix these classes to .fw-wrap and .fw-nowrap, and keep the original classes in the grid for backwards compatibility

**Comment by dariusrosendahl** [comment]
> It think it would be an additional improvement to prefix these classes to .fw-wrap and .fw-nowrap, and keep the original classes in the grid for backwards compatibility

@pascalalferink : Agreed, could you add this to the pullrequest?

**Comment by pascalalferink** [comment]
classnames are modified as requested

**after merging this feature, don't forget to change caslecss-docs**

**Review by dariusrosendahl — APPROVED** [review]

**Pull request merged**
